import { describe, expect, it } from "vitest";
import { branchNameFor, computeExecutionIdentity } from "./identity";
import { CAPABILITY_VERSIONS, EXECUTION_CAPABILITIES, capabilityVersionFor } from "./schema";

/**
 * Execution identity (Sprint 9B §5, §14; post-dogfood §8).
 *
 * Identity decides whether two preparations are "the same work" — and therefore
 * whether the second reuses the first one's branch instead of writing again.
 * That makes every field in it load-bearing: anything that changes the
 * generated bytes but not the identity would silently serve a stale branch as
 * if it were the new output.
 */

const BASE = {
  projectId: "project_1",
  opportunitySetId: "set_1",
  opportunityId: "opportunity_1",
  capability: "nextjs_seo_foundations_v2" as const,
  capabilityVersion: capabilityVersionFor("nextjs_seo_foundations_v2"),
  repositorySnapshotId: "snapshot_1",
  baseSha: "0be0978c72665f84dd7a65e6a19c9415366d8f2b",
};

describe("execution identity", () => {
  it("is stable for identical input", () => {
    expect(computeExecutionIdentity(BASE)).toBe(computeExecutionIdentity(BASE));
  });

  it.each([
    ["a different project", { projectId: "project_2" }],
    ["a different opportunity set", { opportunitySetId: "set_2" }],
    ["a different opportunity", { opportunityId: "opportunity_2" }],
    ["a different snapshot", { repositorySnapshotId: "snapshot_2" }],
    ["a moved base commit", { baseSha: "f".repeat(40) }],
  ])("changes for %s", (_label, override) => {
    expect(computeExecutionIdentity({ ...BASE, ...override })).not.toBe(computeExecutionIdentity(BASE));
  });
});

describe("generator version is part of identity (post-dogfood §8)", () => {
  /**
   * The reason v2 is a new capability rather than an edit to v1.
   *
   * Everything else about a re-preparation can be identical — same project,
   * same opportunity, same snapshot, same base commit — and the generated
   * sitemap will still differ, because the selection rule changed. If identity
   * ignored the version, the user would be shown the old branch, still
   * containing `/login`, as though it were the corrected change.
   */
  it("distinguishes v1 from v2 with every other input held constant", () => {
    const v1 = computeExecutionIdentity({
      ...BASE,
      capability: "nextjs_seo_foundations_v1",
      capabilityVersion: capabilityVersionFor("nextjs_seo_foundations_v1"),
    });

    expect(v1).not.toBe(computeExecutionIdentity(BASE));
    expect(branchNameFor(v1)).not.toBe(branchNameFor(computeExecutionIdentity(BASE)));
  });

  it("changes when only the version string moves", () => {
    // Guards the capability/version pair independently, so a future v3 that
    // reuses a capability id still gets its own identity.
    expect(computeExecutionIdentity({ ...BASE, capabilityVersion: "nextjs-seo-foundations-v9" })).not.toBe(
      computeExecutionIdentity(BASE),
    );
  });

  it("gives every declared capability a distinct version", () => {
    const versions = EXECUTION_CAPABILITIES.map((capability) => CAPABILITY_VERSIONS[capability]);

    expect(new Set(versions).size).toBe(EXECUTION_CAPABILITIES.length);
  });

  it("preserves the historical v1 identity exactly", () => {
    // The first real Vibe-prepared change was claimed under this pair. If this
    // hash ever moves, a stored PreparedChange row stops being findable by the
    // identity that created it.
    expect(
      computeExecutionIdentity({
        ...BASE,
        capability: "nextjs_seo_foundations_v1",
        capabilityVersion: "nextjs-seo-foundations-v1",
      }),
    ).toBe("5a75e68c9f0d7585afb6da2a6407c5fbf6d0f17564d2989bcffc651e5605b19a");
  });
});

describe("branch naming (§18)", () => {
  it("derives a vibe-prefixed branch from the identity hash", () => {
    const identity = computeExecutionIdentity(BASE);

    expect(branchNameFor(identity)).toBe(`vibe/seo-foundations-${identity.slice(0, 12)}`);
  });

  it("carries no opportunity text", () => {
    // Branch names are repository state. Model prose must never reach them.
    expect(branchNameFor(computeExecutionIdentity(BASE))).toMatch(/^vibe\/seo-foundations-[0-9a-f]{12}$/);
  });
});
