import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    "supabase/.temp/**",
    // Generated by the Workflow compiler on every build, not authored here.
    "src/app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
