import { describe, expect, it, vi } from "vitest";
import {
  createBaseIgnorePort,
  isIgnoredByRules,
  matchesKnownBuildArtifact,
  parseGitignore,
  MAX_IGNORE_FILES,
} from "./ignored-paths";

/**
 * Reading a repository's own answer to "was this ever your source?".
 *
 * The rules under test are safety rules with a direction: every error must land
 * on *keeping* a path in the change. A path wrongly kept becomes a diff a human
 * rejects; a path wrongly dropped becomes a change that silently omits work the
 * agent did.
 */

const BASE_SHA = "1f4b0c9d7a2e5f8b3c6d9e0a1b2c3d4e5f607182";

/** The `.gitignore` rules this repository actually had at run `b33635a1`. */
const VIBE_GITIGNORE = [
  "# dependencies",
  "/node_modules",
  "",
  "# testing",
  "/coverage",
  "",
  "# next.js",
  "/.next/",
  "/out/",
  "",
  "# production",
  "/build",
  "",
  "# misc",
  ".DS_Store",
  "*.pem",
  "",
  "# typescript",
  "*.tsbuildinfo",
  "next-env.d.ts",
  "",
  "/.swc",
  "",
  "# Generated by the Workflow compiler (`withWorkflow`) at build time.",
  "src/app/.well-known/workflow/",
].join("\n");

function portOver(files: Record<string, string>, onSkipped?: (d: unknown) => void) {
  const reads: string[] = [];
  const port = createBaseIgnorePort({
    base: {
      async getTextFile(path: string) {
        reads.push(path);
        return files[path] ?? null;
      },
    },
    baseSha: BASE_SHA,
    onSkipped: onSkipped as never,
  });
  return { port, reads };
}

describe("the rules run b33635a1 was measured against", () => {
  /**
   * The twelve paths that turned a six-file change into a seventeen-file
   * rejection, each matched by a rule the repository already had.
   */
  it("withholds every generated path the real run swept up", async () => {
    const { port } = portOver({ ".gitignore": VIBE_GITIGNORE });

    const generated = [
      ".swc/plugins/linux_x86_64_22.0.1/6ea9d3dec20e87696401db15d4c456817f842cb.wasmer-v7",
      ".swc/.gitignore",
      "src/app/.well-known/workflow/v1/step/route.js",
      "src/app/.well-known/workflow/v1/flow/route.js",
      "src/app/.well-known/workflow/v1/manifest.json",
      "src/app/.well-known/workflow/v1/config.json",
      "src/app/.well-known/workflow/v1/step/route.js.debug.json",
      "src/app/.well-known/workflow/v1/flow/route.js.debug.json",
      "src/app/.well-known/workflow/v1/webhook/[token]/route.js",
      "src/app/.well-known/workflow/v1/.gitignore",
      "next-env.d.ts",
      "tsconfig.tsbuildinfo",
    ];

    for (const path of generated) {
      const decision = await port.classify(path);
      expect(decision.ignored, path).toBe(true);
    }
  });

  it("keeps every page the agent actually edited", async () => {
    const { port } = portOver({ ".gitignore": VIBE_GITIGNORE });

    const authored = [
      "src/app/login/page.tsx",
      "src/app/signup/page.tsx",
      "src/app/reset-password/page.tsx",
      "src/app/forgot-password/page.tsx",
      "src/app/layout.tsx",
      "src/app/app/layout.tsx",
    ];

    for (const path of authored) {
      expect((await port.classify(path)).ignored, path).toBe(false);
    }
  });

  it("names the rule that withheld a path, so the decision can be explained", async () => {
    const { port } = portOver({ ".gitignore": VIBE_GITIGNORE });

    const decision = await port.classify("src/app/.well-known/workflow/v1/step/route.js");

    expect(decision).toEqual({
      ignored: true,
      reason: "base_gitignore",
      rule: "src/app/.well-known/workflow/",
    });
  });
});

describe("gitignore syntax, as a deliberate subset", () => {
  const rules = (content: string, directory = "") => parseGitignore(content, directory);

  it("anchors a leading slash to the file's own directory", () => {
    expect(isIgnoredByRules("build/out.js", rules("/build"))).toBe(true);
    expect(isIgnoredByRules("src/build/out.js", rules("/build"))).toBe(false);
    // The same rule inside `src/.gitignore` means `src/build`, not the root's.
    expect(isIgnoredByRules("src/build/out.js", rules("/build", "src"))).toBe(true);
    expect(isIgnoredByRules("build/out.js", rules("/build", "src"))).toBe(false);
  });

  it("matches an unanchored pattern at any depth", () => {
    expect(isIgnoredByRules("a.log", rules("*.log"))).toBe(true);
    expect(isIgnoredByRules("deep/nested/a.log", rules("*.log"))).toBe(true);
    expect(isIgnoredByRules("deep/a.logger.ts", rules("*.log"))).toBe(false);
  });

  it("treats a trailing slash as a directory, and takes everything under it", () => {
    const directoryOnly = rules("src/app/.well-known/workflow/");
    expect(isIgnoredByRules("src/app/.well-known/workflow/v1/a.js", directoryOnly)).toBe(true);
    // A *file* of that exact name is not the directory the rule names.
    expect(isIgnoredByRules("src/app/.well-known/workflow", directoryOnly)).toBe(false);
  });

  it("lets a later negation re-include", () => {
    expect(isIgnoredByRules("keep.log", rules("*.log\n!keep.log"))).toBe(false);
    expect(isIgnoredByRules("other.log", rules("*.log\n!keep.log"))).toBe(true);
  });

  /** A nested `.gitignore` is applied after the root's, so it wins. */
  it("lets a nested file overrule the root", async () => {
    const { port } = portOver({
      ".gitignore": "*.log",
      "src/.gitignore": "!important.log",
    });

    expect((await port.classify("src/important.log")).ignored).toBe(false);
    expect((await port.classify("other.log")).ignored).toBe(true);
  });

  it("ignores comments, blanks and over-long rules", () => {
    const parsed = rules(["# a comment", "", "   ", "*.log", "x".repeat(400)].join("\n"));
    expect(parsed).toHaveLength(1);
  });

  it("handles `**` across directories", () => {
    expect(isIgnoredByRules("a/b/c/gen.ts", rules("a/**/gen.ts"))).toBe(true);
    expect(isIgnoredByRules("a/gen.ts", rules("a/**/gen.ts"))).toBe(true);
    expect(isIgnoredByRules("b/gen.ts", rules("a/**/gen.ts"))).toBe(false);
  });

  /**
   * An unrecognised construct must fail to match rather than match everything.
   * Bracket classes are escaped to literals, which errs towards keeping a path.
   */
  it("treats a bracket class as literal text rather than as syntax", () => {
    expect(isIgnoredByRules("a.ts", rules("[ab].ts"))).toBe(false);
    expect(isIgnoredByRules("[ab].ts", rules("[ab].ts"))).toBe(true);
  });
});

describe("bounded, because .gitignore is untrusted repository content", () => {
  it("reads only the directories a queried path lives under", async () => {
    const { port, reads } = portOver({ ".gitignore": VIBE_GITIGNORE });

    await port.classify("src/app/login/page.tsx");

    expect(reads).toEqual([
      ".gitignore",
      "src/.gitignore",
      "src/app/.gitignore",
      "src/app/login/.gitignore",
    ]);
  });

  it("reads each directory once, however many paths ask about it", async () => {
    const { port, reads } = portOver({ ".gitignore": VIBE_GITIGNORE });

    await port.classify("src/app/a.tsx");
    await port.classify("src/app/b.tsx");
    await port.classify("src/app/c.tsx");

    expect(reads).toEqual([".gitignore", "src/.gitignore", "src/app/.gitignore"]);
  });

  it("stops reading at the file budget and says so", async () => {
    const skipped: unknown[] = [];
    const { port } = portOver({}, (detail) => skipped.push(detail));

    // One deep path is enough to exhaust the budget on its own.
    const deep = Array.from({ length: MAX_IGNORE_FILES + 5 }, (_, i) => `d${i}`).join("/");
    await port.classify(`${deep}/file.ts`);

    expect(skipped.length).toBeGreaterThan(0);
    expect(skipped[0]).toMatchObject({ reason: "budget" });
  });

  /** A read that throws must not fail an execution, and must not suppress. */
  it("suppresses nothing when the rules cannot be read", async () => {
    const port = createBaseIgnorePort({
      base: {
        async getTextFile() {
          throw new Error("github is having a day");
        },
      },
      baseSha: BASE_SHA,
    });

    expect((await port.classify("src/app/page.tsx")).ignored).toBe(false);
  });

  it("caps how many rules one file contributes", () => {
    const enormous = Array.from({ length: 2000 }, (_, i) => `pattern-${i}/`).join("\n");
    expect(parseGitignore(enormous).length).toBeLessThanOrEqual(500);
  });
});

describe("defense in depth, for a repository that declared nothing", () => {
  it("still withholds the common build and cache artifacts", async () => {
    const { port } = portOver({});

    for (const path of [
      ".swc/plugins/x.wasmer-v7",
      ".cache/webpack/index.pack",
      "out/index.html",
      ".pnpm-store/v3/files/00/abc",
      "tsconfig.tsbuildinfo",
      "packages/web/tsconfig.tsbuildinfo",
      "next-env.d.ts",
    ]) {
      const decision = await port.classify(path);
      expect(decision.ignored, path).toBe(true);
      if (decision.ignored) expect(decision.reason).toBe("known_build_artifact");
    }
  });

  it("does not touch ordinary source that merely resembles those names", () => {
    expect(matchesKnownBuildArtifact("src/lib/out-of-band.ts")).toBeNull();
    expect(matchesKnownBuildArtifact("src/cache.ts")).toBeNull();
    expect(matchesKnownBuildArtifact("src/next-env.ts")).toBeNull();
  });

  /**
   * The list is a fallback for repositories that stated no intent. One that
   * states the opposite is not overruled by it.
   */
  it("yields to an explicit re-inclusion in the repository's own rules", async () => {
    const { port } = portOver({ ".gitignore": "!out/keep.js" });

    expect((await port.classify("out/keep.js")).ignored).toBe(false);
    expect((await port.classify("out/other.js")).ignored).toBe(true);
  });
});

describe("the agent cannot rewrite the rules it is judged by", () => {
  /**
   * The agent held write access to the workspace for the whole run, `.gitignore`
   * included. Every read here goes to the pinned base commit, so a `.gitignore`
   * edited during the run has no effect on which of its own output is withheld.
   */
  it("reads every rule at the pinned base commit", async () => {
    const getTextFile = vi.fn(async () => VIBE_GITIGNORE);
    const port = createBaseIgnorePort({
      base: { getTextFile },
      baseSha: BASE_SHA,
    });

    await port.classify("src/app/page.tsx");

    expect(getTextFile).toHaveBeenCalled();
    for (const call of getTextFile.mock.calls as unknown as [string, string, number][]) {
      expect(call[1]).toBe(BASE_SHA);
    }
  });
});
