import type { SupabaseClient } from "@supabase/supabase-js";
import { findAgentRunByOperation } from "@/modules/coding-agent/store";
import { findExecutionSpecByIdentity } from "@/modules/execution-contract/store";
import { loadPlanStep } from "@/modules/execution-context/service";
import type { StoredPreparedChange } from "@/modules/execution/store";
import { resolveValidationDepth, type ValidationDepthResolution } from "./depth";

/**
 * Gathering the trusted inputs the depth resolver needs (Sprint 0047).
 *
 * ## Why this is one function and not two
 *
 * The depth is part of `validation_identity`, and the identity is computed in
 * two places: `validation/service.ts` decides whether an existing run can be
 * reused, and `operations/change-validation/execution.ts` claims the row. If
 * those two computed the depth differently — even once — the reuse check would
 * look for a hash the claim never wrote, and every validation would provision a
 * fresh sandbox for a question that was already answered.
 *
 * So both call this, and neither has a private path to a depth.
 *
 * ## Degrading, deliberately upward
 *
 * Every lookup below is allowed to fail. A deterministic capability has no
 * agent run; an agent run may predate the spec it names; a plan step may have
 * been reworded or removed. None of that is an error — it is missing signal,
 * and missing signal resolves to `standard` in `resolveValidationDepth`, never
 * to `fast`.
 *
 * The one input that is never missing is the changed path list, which comes
 * straight off the prepared change Vibe itself verified. That is also the input
 * that can force `deep` on its own, so the escalation rules keep working even
 * when every other lookup returns nothing.
 */

export type DepthInputSources = {
  supabase: SupabaseClient;
  projectId: string;
  prepared: Pick<StoredPreparedChange, "operationRunId" | "files">;
};

export async function resolveDepthForPreparedChange(
  input: DepthInputSources,
): Promise<ValidationDepthResolution> {
  const changedPaths = input.prepared.files.map((file) => file.path);

  const step = await loadTrustedStepContext(input);

  return resolveValidationDepth({
    riskClass: step?.riskClass ?? null,
    changeKind: step?.changeKind ?? null,
    evidenceIds: step?.evidenceIds ?? [],
    changedPaths,
  });
}

/**
 * The spec's risk class and the Action Step's own structured fields.
 *
 * Reached through the agent execution run that produced this prepared change —
 * `prepared.operationRunId` is the *agent's* operation, not the validation's —
 * and then through the spec it names. A deterministic capability has no agent
 * run at all and returns null here, which is correct: those changes are
 * generated by Vibe's own code from a fixed template, and nothing about them is
 * classifiable from an Action Step.
 */
async function loadTrustedStepContext(input: DepthInputSources) {
  try {
    const agentRun = await findAgentRunByOperation(input.supabase, input.prepared.operationRunId);
    if (!agentRun) return null;

    const { data } = await input.supabase
      .from("execution_specs")
      .select("spec_identity")
      .eq("id", agentRun.executionSpecId)
      .eq("project_id", input.projectId)
      .maybeSingle();

    const specIdentity = (data as { spec_identity: string } | null)?.spec_identity;
    if (!specIdentity) return null;

    const stored = await findExecutionSpecByIdentity(input.supabase, {
      projectId: input.projectId,
      specIdentity,
    });
    if (!stored) return null;

    // The same fixture-then-database lookup the Context Compiler and Agent
    // Verification already use. A benchmark fixture resolves here exactly as a
    // customer's plan step does.
    const planStep = await loadPlanStep({
      supabase: input.supabase,
      projectId: input.projectId,
      spec: stored.spec,
    });

    return {
      riskClass: stored.spec.riskClass,
      changeKind: planStep?.changeKind ?? null,
      evidenceIds: planStep?.evidenceIds ?? [],
    };
  } catch {
    // A read failure is missing signal, not a reason to fail a validation the
    // user asked for. `resolveValidationDepth` treats it as `standard`.
    return null;
  }
}
