import type { RouteSummary } from "@/modules/repository-intelligence/schema";

/**
 * Which routes may appear in a generated sitemap (Sprint 9 post-dogfood §3, §4).
 *
 * ## Why this file exists
 *
 * The first real execution wrote a sitemap listing `/`, `/login` and `/signup`.
 * Nothing unsafe happened — the bytes written were exactly the bytes intended,
 * verified by read-back — but a sitemap is a public invitation to index, and
 * inviting a search engine to index a login form is not what anyone asked for.
 *
 * That is the distinction the dogfood surfaced: `repository_write_verified`
 * says the write was correct, not that the *content* was good. This module is
 * the content half, and it is deliberately dull.
 *
 * ## The rule
 *
 * A route is a sitemap candidate only when it is a **static page route outside
 * every known authentication, account, application, API and administrative
 * surface**. Everything else is omitted.
 *
 * The bias is explicit and one-directional: **when in doubt, omit.** A missing
 * marketing page costs a little organic reach that a human can restore in one
 * line. A published `/reset-password` costs a private surface advertised to
 * every crawler on the internet, and cannot be un-published. For V0.1 that
 * trade is not close.
 *
 * ## What it never reads
 *
 * Only `RouteSummary` — structured route intelligence derived from repository
 * *paths*, never file contents and never model output. An opportunity's title,
 * problem text or evidence prose cannot influence which URLs are published,
 * for the same reason it cannot influence which files are written: model
 * wording is not a machine API.
 */

export const SITEMAP_EXCLUSION_REASONS = [
  /** A layout, or an API route handler rather than a page. */
  "not_a_page",
  /** `/blog/[slug]` — a template, not a URL. Enumerating it needs real data. */
  "dynamic_route",
  /** Sign-in, sign-up, password recovery, callbacks. */
  "authentication_surface",
  /** The signed-in product itself. */
  "application_surface",
  /** Account, billing and settings surfaces. */
  "account_surface",
  "api_surface",
  "administrative_surface",
] as const;
export type SitemapExclusionReason = (typeof SITEMAP_EXCLUSION_REASONS)[number];

export type RouteClassification =
  | { indexable: true }
  | { indexable: false; reason: SitemapExclusionReason };

/**
 * First-segment classification.
 *
 * Matching on the first segment means a rule covers the whole subtree:
 * excluding `app` excludes `/app/projects/123` without needing to know it
 * exists. These are conventional names, so the list is a heuristic — which is
 * precisely why it may only ever *remove* routes, never add one.
 */
const EXCLUDED_FIRST_SEGMENTS: ReadonlyMap<string, SitemapExclusionReason> = new Map([
  // Authentication and credential recovery.
  ["login", "authentication_surface"],
  ["logout", "authentication_surface"],
  ["signin", "authentication_surface"],
  ["sign-in", "authentication_surface"],
  ["signout", "authentication_surface"],
  ["sign-out", "authentication_surface"],
  ["signup", "authentication_surface"],
  ["sign-up", "authentication_surface"],
  ["register", "authentication_surface"],
  ["forgot-password", "authentication_surface"],
  ["reset-password", "authentication_surface"],
  ["verify-email", "authentication_surface"],
  ["auth", "authentication_surface"],

  // The signed-in product.
  ["app", "application_surface"],
  ["dashboard", "application_surface"],

  // Account management.
  ["account", "account_surface"],
  ["settings", "account_surface"],
  ["billing", "account_surface"],

  ["api", "api_surface"],
  ["admin", "administrative_surface"],
]);

function firstSegment(routePath: string): string {
  return routePath.split("/").filter((segment) => segment.length > 0)[0] ?? "";
}

/**
 * Is this route safe to advertise to search engines?
 *
 * Surface classification is checked before route kind so the reason stays
 * meaningful: `/api/webhook` is an API surface, which is a more useful thing to
 * report than "not a page".
 */
export function classifyRouteForSitemap(route: RouteSummary): RouteClassification {
  const excluded = EXCLUDED_FIRST_SEGMENTS.get(firstSegment(route.path));
  if (excluded !== undefined) return { indexable: false, reason: excluded };

  // A dynamic segment is a template. Turning `/blog/[slug]` into real URLs
  // would mean reading the customer's data, which this capability does not do.
  if (route.dynamic) return { indexable: false, reason: "dynamic_route" };

  if (route.kind !== "page") return { indexable: false, reason: "not_a_page" };

  return { indexable: true };
}

/**
 * The public routes a sitemap may list, deduplicated and ordered.
 *
 * `/` is excluded here and added by the generator instead: the site root is the
 * verified production origin itself, so it does not depend on route detection
 * having worked. Ordering is alphabetical purely so the generated bytes are
 * stable — identical inputs must produce an identical hash (§25).
 */
export function selectSitemapRoutes(routes: readonly RouteSummary[]): string[] {
  const selected = new Set<string>();

  for (const route of routes) {
    if (route.path === "/") continue;
    if (!classifyRouteForSitemap(route).indexable) continue;
    selected.add(route.path);
  }

  return [...selected].sort();
}

/**
 * Exclusion reasons that are a *claim about the surface*, not about our
 * ability to enumerate it (Sprint 12A §5).
 *
 * The distinction matters for outcome verification. `/blog/[slug]` is left out
 * of a sitemap because a template is not a URL — nobody is asserting it must
 * never be indexed, and it cannot appear literally anyway. `/login` is left out
 * because advertising a sign-in form to every crawler on the internet is the
 * defect v2 exists to fix.
 *
 * Only the second kind is worth verifying in production, and only the second
 * kind may be reported as a *failed* expectation if it shows up.
 */
const SURFACE_EXCLUSION_REASONS: ReadonlySet<SitemapExclusionReason> = new Set([
  "authentication_surface",
  "application_surface",
  "account_surface",
  "api_surface",
  "administrative_surface",
]);

/**
 * The private subtrees this capability asserts must not appear in the sitemap.
 *
 * Returned as **first-segment prefixes** rather than full route paths, because
 * that is exactly what the exclusion rule above operates on: excluding `app`
 * excludes `/app/projects/123` without anyone having enumerated it. Verifying
 * the prefix therefore verifies the rule, while verifying twelve individual
 * paths would verify twelve samples of it.
 *
 * Only segments the analyzed repository actually contains are returned. A
 * repository with no `/admin` route gets no `/admin` expectation — asserting the
 * absence of a page that never existed would manufacture a check that can only
 * ever pass, which is worse than no check at all because it inflates the
 * evidence list.
 *
 * Ordering is by exclusion reason (authentication first, because that is the
 * defect this capability was version-bumped for) and then alphabetical, so the
 * expectation snapshot is deterministic and a truncation drops the least
 * consequential entries rather than an arbitrary tail.
 */
export function excludedSurfacePrefixes(routes: readonly RouteSummary[]): string[] {
  const REASON_PRIORITY: readonly SitemapExclusionReason[] = [
    "authentication_surface",
    "account_surface",
    "administrative_surface",
    "application_surface",
    "api_surface",
  ];

  const bySegment = new Map<string, SitemapExclusionReason>();

  for (const route of routes) {
    const segment = firstSegment(route.path);
    if (segment === "") continue;

    const reason = EXCLUDED_FIRST_SEGMENTS.get(segment);
    if (reason === undefined || !SURFACE_EXCLUSION_REASONS.has(reason)) continue;

    bySegment.set(segment, reason);
  }

  return [...bySegment.entries()]
    .sort(([leftSegment, leftReason], [rightSegment, rightReason]) => {
      const byReason =
        REASON_PRIORITY.indexOf(leftReason) - REASON_PRIORITY.indexOf(rightReason);
      return byReason !== 0 ? byReason : leftSegment.localeCompare(rightSegment);
    })
    .map(([segment]) => `/${segment}`);
}
